org: adrianmg
app: api
service: api

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-3
  stage: dev
  environment:
    SECRET_KEY: ${env:SECRET_KEY}
    MONGO_URI: ${env:MONGO_URI}
    ATLAS_PASSWORD: ${env:ATLAS_PASSWORD}
    ATLAS_USER: ${env:ATLAS_USER}
  httpApi:
    cors: true

functions:
  api:
    handler: src/server.handler
    events:
      - httpApi: "*"
