org: adrianmg
app: api
service: api

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-3
  stage: dev
  environment:
    SECRET_KEY: ${env:SECRET_KEY}
    MONGO_URI: ${env:MONGO_URI}
    ATLAS_PASSWORD: ${env:ATLAS_PASSWORD}
    ATLAS_USER: ${env:ATLAS_USER}
  httpApi:
    cors:
      allowedOrigins:
        - http://hotel-miranda-admin.s3-website.eu-west-3.amazonaws.com
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization

functions:
  api:
    handler: src/server.handler
    events:
      - httpApi: "*"
